name: Test

on:
  - pull_request
  - push

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npx xo

  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run build
      - run: npm run demo:build

  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get install xvfb
          # Ensure both a Chromium and a Firefox binary are available.
          PUPPETEER_PRODUCT=firefox npm install
          npm install
      - name: Run unit tests
        uses: nick-invision/retry@v2
        env:
          CHROMIUM: true
        with:
          max_attempts: 3
          command: xvfb-run --auto-servernum npm run jest
          timeout_minutes: 10
